version: "3.4"

name: webhook-trader
services:
    trade-server:
        build: .
        container_name: webhook-server
        env_file: ".env"
        ports:
            - "8000:8000"
        volumes:
            - ~/logs:/code/logs
            - ./track_order_id:/code/track_order_id
        restart: always
